import 'normalize.css'
import '../components/menu/menu'
import '../components/header/header'
import '../components/fonts/_fonts.scss'
import '../components/block-about-us/block-about-us'
import '../components/indicators/indicators'

import '../pages/index/index-mobile.scss'
import '../pages/index/index'
import '../pages/index/index.scss'